name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - run: npm install

      - name: Run Tests
        run: |
          chmod +x ./node_modules/.bin/jest
          ./node_modules/.bin/jest
